CONFIG_GPIO=y

CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y

CONFIG_ASSERT=n

CONFIG_I2C=y
CONFIG_I2C_TARGET=y

CONFIG_TEST_RANDOM_GENERATOR=n
CONFIG_TIMER_RANDOM_GENERATOR=n

# for events
CONFIG_EVENTS=y

# Board specific macros
# CONFIG_HAS_AUTO_RESET=y
CONFIG_OLED_USE_MEMCPY=y
CONFIG_PONG_DEBUG=n
CONFIG_PONG_TEST_PAGE=y

# Stack stuff
# CONFIG_MAIN_STACK_SIZE=1024

# Thread analyzer
# CONFIG_THREAD_ANALYZER=y
# CONFIG_THREAD_ANALYZER_USE_LOG=y
# CONFIG_THREAD_ANALYZER_AUTO=y
# CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=30
# CONFIG_THREAD_NAME=y

CONFIG_DEBUG=n
# CONFIG_DEBUG_THREAD_INFO=y
